---
env:
  pre_settings: []
  modules:[]
  drush_commands:[]
  post_settings:
    - { name: '$conf["error_level"]', status: true, value: '2' }
    - { name: '$conf["cache"]', status: true, value: '0' }
    - { name: '$conf["block_cache"]', status: true, value: '0' }
    - { name: '$conf["preprocess_css"]', status: true, value: '0' }
    - { name: '$conf["preprocess_js"]', status: true, value: '0' }
    #- { name: '$conf["stage_file_proxy_origin"]', status: false, value: "{{ origin_site_url }}" }
