---
env:
  pre_settings: []
  modules: []
  drush_commands: []
  post_settings:
    - { name: '$conf["error_level"]', status: true, value: '0' }
    # - { name: '$conf["stage_file_proxy_origin"]', status: false, value: "{{ origin_site_url }}" }
